# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from interface_fonctions import *
from data_import import json_import
from tools import Person

class Ui_MainWindow(object):

    student = Person(r'', 'RannouP', 'Right', 'Pierre_Rannou')
    liste_descripteurs = []
    expert_data_repartion = {}
    def initialise(self) :
        leaning = QtWidgets.QTreeWidgetItem(self.defauts_treeView, ["Leaning"])
        meanSpeed = QtWidgets.QTreeWidgetItem(leaning, ["MeanSpeed"])
        QtWidgets.QTreeWidgetItem(meanSpeed, ["LeftShoulder", "False"])
        QtWidgets.QTreeWidgetItem(meanSpeed, ["RightShoulder", "False"])

        elbowMove = QtWidgets.QTreeWidgetItem(self.defauts_treeView, ["Elbow_Move"])
        meanSpeed = QtWidgets.QTreeWidgetItem(elbowMove, ["MeanSpeed"])
        QtWidgets.QTreeWidgetItem(meanSpeed, ["LeftArm", "True"])
        QtWidgets.QTreeWidgetItem(meanSpeed, ["LeftShoulder", "True"])

        javelin = QtWidgets.QTreeWidgetItem(self.defauts_treeView, ["Javelin"])
        distanceX = QtWidgets.QTreeWidgetItem(javelin, ["DistanceX"])
        QtWidgets.QTreeWidgetItem(distanceX, ["distanceRightHandHead", "True"])
        distanceY = QtWidgets.QTreeWidgetItem(javelin, ["Distance Y"])
        QtWidgets.QTreeWidgetItem(distanceY, ["distanceRightHandHead", "True"])
        distanceZ = QtWidgets.QTreeWidgetItem(javelin, ["Distance Z"])
        QtWidgets.QTreeWidgetItem(distanceZ, ["distanceRightHandHead", "True"])

        alignArm = QtWidgets.QTreeWidgetItem(self.defauts_treeView, ["Align_Arm"])
        boundingBowWithMean = QtWidgets.QTreeWidgetItem(alignArm, ["BoundingBoxWidthMean"])
        QtWidgets.QTreeWidgetItem(boundingBowWithMean, ["HeadRightShoulderRightArmRightForeArmRightHand", "True"])
        boundingBoxWidthStd = QtWidgets.QTreeWidgetItem(alignArm, ["BoundingBoxWidthStd"])
        QtWidgets.QTreeWidgetItem(boundingBoxWidthStd, ["HeadRightShoulderRightArmRightForeArmRightHand", "True"])

        self.btn_valider.clicked.connect(self.on_btn_valider_clicked)
        self.btn_parcourir.clicked.connect(self.data_path_explorer)
        self.path_explore_button.clicked.connect(self.data_path_explorer)
        self.load_button.clicked.connect(self.load_joints_data)
        self.descriptor_box.currentIndexChanged.connect(self.refresh_joints_display)
        self.add_articulation_button.clicked.connect(self.add_articulation)
        self.add_button.clicked.connect(self.add_new_default)
        self.defaut_name_edit.textEdited.connect(self.activer_add_button)
        self.articulation_display.currentItemChanged.connect(self.activer_articulation_button)
        self.hide_descriptor_page()

    def activer_add_button(self) :
        if (self.defaut_name_edit.text() == "") :
            self.add_button.setEnabled(False)
        else : 
            self.add_button.setEnabled(True)

    def activer_articulation_button(self) :
        self.add_articulation_button.setEnabled(True)

    def on_btn_valider_clicked(self):
        expert = Person(r'', 'aurel', 'Right')
        path = self.data_path_edit_2.text()
        datatype_joints_list = []
        root = self.defauts_treeView.invisibleRootItem()
        for defaut in range (root.childCount()) :
            defaut_actuel = root.child(defaut) 
            descripteurs = {}
            for descripteur in range (defaut_actuel.childCount()) :
                articulations = []
                descripteur_actuel = defaut_actuel.child(descripteur)
                nom = descripteur_actuel.text(0)

                for articulation in range (descripteur_actuel.childCount()) :
                    articulation_actuelle = descripteur_actuel.child(articulation)
                    if (articulation_actuelle.text(1) == "False") :
                        articulations.append({'joint' : articulation_actuelle.text(0), 'laterality' : False})
                    else :
                        articulations.append({'joint' : articulation_actuelle.text(0), 'laterality' : True})
                descripteurs[nom.replace(" ", "")] = articulations
            datatype_joints_list.append([str.lower(defaut_actuel.text(0)), descripteurs])    
        only_feedback_new_descriptors(expert, self.student, path, datatype_joints_list, self.expert_data_repartion)

    def data_path_explorer(self) :
        explorer = QtWidgets.QFileDialog()
        explorer.setFileMode(QtWidgets.QFileDialog.Directory)
        explorer.exec_()
        self.data_path_edit.setText(explorer.selectedFiles()[0])
        self.data_path_edit_2.setText(explorer.selectedFiles()[0])
        self.load_button.setEnabled(True)
        return

    def load_joints_data(self) :
        path = self.data_path_edit.text()
        datatypes_list = get_datatypes_names(path, self.student.name)
        datatype = datatypes_list[0]
        joints_list = get_joint_list(path, self.student.name, datatype)

        self.descriptor_label.show()
        self.descriptor_box.show()
        self.articulation_display.show()
        self.add_articulation_button.show()
        self.lateralite_check.show()

        self.descriptor_box.addItems(datatypes_list)
        self.articulation_display.addItems(joints_list)

    def refresh_joints_display(self) :
        path = self.data_path_edit.text()
        datatype = self.descriptor_box.currentText()
        joints_list = get_joint_list(path, self.student.name, datatype)
        self.articulation_display.clear()
        self.articulation_display.addItems(joints_list)

    def hide_descriptor_page(self) :
        self.descriptor_label.hide()
        self.descriptor_box.hide()
        self.articulation_display.hide()
        self.add_articulation_button.hide()
        self.lateralite_check.hide()
        self.defaut_name_label.hide()
        self.defaut_name_edit.hide()
        self.default_tree_recap.hide()
        self.add_button.hide()
        self.label_4.hide()
        self.label_5.hide()
        self.label_6.hide()
        self.expert_data_max_index.hide()
        self.expert_data_min_index.hide()

        self.load_button.setEnabled(False)
        self.add_button.setEnabled(False)
        self.add_articulation_button.setEnabled(False)

    def add_articulation(self) :
        self.defaut_name_label.show()
        self.defaut_name_edit.show()
        self.default_tree_recap.show()
        self.add_button.show()
        self.label_4.show()
        self.label_5.show()
        self.label_6.show()
        self.expert_data_min_index.show()
        self.expert_data_max_index.show()

        self.add_articulation_button.setEnabled(False)

        datatype = self.descriptor_box.currentText()
        articulation = self.articulation_display.currentItem().text()
        for descripteur in self.liste_descripteurs :
            if (descripteur[0] == datatype) :
                articulation = self.articulation_display.currentItem().text()
                QtWidgets.QTreeWidgetItem(descripteur[1], [articulation, str(self.lateralite_check.isChecked())])
                self.articulation_display.currentItem().setFlags(QtCore.Qt.NoItemFlags)
                return  

        datatype_display = QtWidgets.QTreeWidgetItem(self.default_tree_recap, [datatype])
        articulation = self.articulation_display.currentItem().text()
        QtWidgets.QTreeWidgetItem(datatype_display, [articulation, str(self.lateralite_check.isChecked())])    
        self.liste_descripteurs.append([datatype, datatype_display])   
        self.articulation_display.currentItem().setFlags(QtCore.Qt.NoItemFlags)

    def add_new_default(self):
        self.tabSecondaire.setCurrentIndex(2)
        new_default = QtWidgets.QTreeWidgetItem(self.defauts_treeView, [self.defaut_name_edit.text()])
        root = self.default_tree_recap.invisibleRootItem()
        for i in range (root.childCount()) :
            enfant = root.child(i) 
            descripteur = QtWidgets.QTreeWidgetItem(new_default, [enfant.text(0)])
            for j in range (enfant.childCount()) :
                QtWidgets.QTreeWidgetItem(descripteur, [enfant.child(j).text(0), enfant.child(j).text(1)])
        self.expert_data_repartion[str.lower(self.defaut_name_edit.text())] = [x+1 for x in range(self.expert_data_min_index.value(), self.expert_data_max_index.value())]
        self.default_tree_recap.clear()
        self.defaut_name_edit.clear()
        self.articulation_display.clear()
        self.descriptor_box.setCurrentIndex(0)
        self.load_joints_data()
        return

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(459, 532)
        self.tabPrincipal = QtWidgets.QTabWidget(MainWindow)
        self.tabPrincipal.setGeometry(QtCore.QRect(0, 0, 461, 491))
        self.tabPrincipal.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabPrincipal.setObjectName("tabPrincipal")
        self.basicsTab = QtWidgets.QWidget()
        self.basicsTab.setObjectName("basicsTab")
        self.pb_box = QtWidgets.QGroupBox(self.basicsTab)
        self.pb_box.setGeometry(QtCore.QRect(0, 20, 451, 121))
        self.pb_box.setObjectName("pb_box")
        self.pb_leaning_check = QtWidgets.QCheckBox(self.pb_box)
        self.pb_leaning_check.setGeometry(QtCore.QRect(30, 20, 70, 17))
        self.pb_leaning_check.setObjectName("pb_leaning_check")
        self.pb_leaning_check.setChecked(True)
        self.pb_elbow_check = QtWidgets.QCheckBox(self.pb_box)
        self.pb_elbow_check.setGeometry(QtCore.QRect(30, 40, 101, 17))
        self.pb_elbow_check.setObjectName("pb_elbow_check")
        self.pb_elbow_check.setChecked(True)
        self.pb_arm_check = QtWidgets.QCheckBox(self.pb_box)
        self.pb_arm_check.setGeometry(QtCore.QRect(30, 60, 101, 17))
        self.pb_arm_check.setObjectName("pb_arm_check")
        self.pb_arm_check.setChecked(True)
        self.pb_javelin_check = QtWidgets.QCheckBox(self.pb_box)
        self.pb_javelin_check.setGeometry(QtCore.QRect(30, 80, 70, 17))
        self.pb_javelin_check.setObjectName("pb_javelin_check")
        self.pb_javelin_check.setChecked(True)
        self.data_box = QtWidgets.QGroupBox(self.basicsTab)
        self.data_box.setGeometry(QtCore.QRect(0, 150, 451, 91))
        self.data_box.setObjectName("data_box")
        self.data_path_edit = QtWidgets.QLineEdit(self.data_box)
        self.data_path_edit.setGeometry(QtCore.QRect(20, 30, 261, 20))
        self.data_path_edit.setObjectName("data_path_edit")
        self.btn_parcourir = QtWidgets.QPushButton(self.data_box)
        self.btn_parcourir.setGeometry(QtCore.QRect(290, 30, 75, 23))
        self.btn_parcourir.setDefault(False)
        self.btn_parcourir.setFlat(False)
        self.btn_parcourir.setObjectName("btn_parcourir")
        self.msg_data_path = QtWidgets.QLabel(self.data_box)
        self.msg_data_path.setGeometry(QtCore.QRect(120, 60, 151, 16))
        self.msg_data_path.setObjectName("msg_data_path")
        self.tabPrincipal.addTab(self.basicsTab, "")
        self.advancedTab = QtWidgets.QWidget()
        self.advancedTab.setObjectName("advancedTab")
        self.tabSecondaire = QtWidgets.QTabWidget(self.advancedTab)
        self.tabSecondaire.setGeometry(QtCore.QRect(0, 0, 451, 471))
        self.tabSecondaire.setObjectName("tabSecondaire")
        self.algorithmTab = QtWidgets.QWidget()
        self.algorithmTab.setObjectName("algorithmTab")
        self.data_treatment_box = QtWidgets.QGroupBox(self.algorithmTab)
        self.data_treatment_box.setGeometry(QtCore.QRect(0, 10, 441, 141))
        self.data_treatment_box.setObjectName("data_treatment_box")
        self.scale_check = QtWidgets.QCheckBox(self.data_treatment_box)
        self.scale_check.setGeometry(QtCore.QRect(30, 20, 131, 31))
        self.scale_check.setObjectName("scale_check")
        self.normalize_check = QtWidgets.QCheckBox(self.data_treatment_box)
        self.normalize_check.setGeometry(QtCore.QRect(30, 50, 131, 31))
        self.normalize_check.setObjectName("normalize_check")
        self.algorithms_box = QtWidgets.QGroupBox(self.algorithmTab)
        self.algorithms_box.setGeometry(QtCore.QRect(0, 160, 441, 171))
        self.algorithms_box.setObjectName("algorithms_box")
        self.comboBox = QtWidgets.QComboBox(self.algorithms_box)
        self.comboBox.setGeometry(QtCore.QRect(140, 30, 121, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(self.algorithms_box)
        self.label_2.setGeometry(QtCore.QRect(30, 30, 111, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.algorithms_box)
        self.label_3.setGeometry(QtCore.QRect(30, 70, 111, 16))
        self.label_3.setObjectName("label_3")
        self.spinBox = QtWidgets.QSpinBox(self.algorithms_box)
        self.spinBox.setGeometry(QtCore.QRect(150, 70, 42, 22))
        self.spinBox.setObjectName("spinBox")
        self.display_box = QtWidgets.QGroupBox(self.algorithmTab)
        self.display_box.setGeometry(QtCore.QRect(0, 340, 441, 91))
        self.display_box.setObjectName("display_box")
        self.display_check = QtWidgets.QCheckBox(self.display_box)
        self.display_check.setGeometry(QtCore.QRect(30, 30, 131, 31))
        self.display_check.setObjectName("display_check")
        self.tabSecondaire.addTab(self.algorithmTab, "")
        self.descriptorsTab = QtWidgets.QWidget()
        self.descriptorsTab.setObjectName("descriptorsTab")
        self.data_path_label = QtWidgets.QLabel(self.descriptorsTab)
        self.data_path_label.setGeometry(QtCore.QRect(10, 10, 47, 16))
        self.data_path_label.setObjectName("data_path_label")
        self.path_explore_button = QtWidgets.QPushButton(self.descriptorsTab)
        self.path_explore_button.setGeometry(QtCore.QRect(210, 10, 75, 23))
        self.path_explore_button.setObjectName("path_explore_button")
        self.load_button = QtWidgets.QPushButton(self.descriptorsTab)
        self.load_button.setGeometry(QtCore.QRect(290, 10, 111, 23))
        self.load_button.setObjectName("load_button")
        self.data_path_edit_2 = QtWidgets.QLineEdit(self.descriptorsTab)
        self.data_path_edit_2.setGeometry(QtCore.QRect(80, 10, 113, 20))
        self.data_path_edit_2.setObjectName("data_path_edit_2")
        self.descriptor_label = QtWidgets.QLabel(self.descriptorsTab)
        self.descriptor_label.setGeometry(QtCore.QRect(10, 50, 61, 21))
        self.descriptor_label.setObjectName("descriptor_label")
        self.descriptor_box = QtWidgets.QComboBox(self.descriptorsTab)
        self.descriptor_box.setGeometry(QtCore.QRect(80, 50, 101, 22))
        self.descriptor_box.setObjectName("descriptor_box")
        self.add_articulation_button = QtWidgets.QPushButton(self.descriptorsTab)
        self.add_articulation_button.setGeometry(QtCore.QRect(100, 110, 75, 23))
        self.add_articulation_button.setObjectName("add_articulation_button")
        self.lateralite_check = QtWidgets.QCheckBox(self.descriptorsTab)
        self.lateralite_check.setGeometry(QtCore.QRect(250, 200, 70, 17))
        self.lateralite_check.setObjectName("lateralite_check")
        self.defaut_name_edit = QtWidgets.QLineEdit(self.descriptorsTab)
        self.defaut_name_edit.setGeometry(QtCore.QRect(250, 260, 181, 20))
        self.defaut_name_edit.setObjectName("defaut_name_edit")
        self.add_button = QtWidgets.QPushButton(self.descriptorsTab)
        self.add_button.setGeometry(QtCore.QRect(250, 360, 75, 23))
        self.add_button.setObjectName("add_button")
        self.defaut_name_label = QtWidgets.QLabel(self.descriptorsTab)
        self.defaut_name_label.setGeometry(QtCore.QRect(250, 240, 81, 16))
        self.defaut_name_label.setObjectName("defaut_name_label")
        self.articulation_display = QtWidgets.QListWidget(self.descriptorsTab)
        self.articulation_display.setGeometry(QtCore.QRect(190, 40, 251, 151))
        self.articulation_display.setObjectName("articulation_display")
        self.default_tree_recap = QtWidgets.QTreeWidget(self.descriptorsTab)
        self.default_tree_recap.setGeometry(QtCore.QRect(10, 230, 231, 191))
        self.default_tree_recap.setObjectName("default_tree_recap")
        self.tabSecondaire.addTab(self.descriptorsTab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.defauts_treeView = QtWidgets.QTreeWidget(self.tab)
        self.defauts_treeView.setGeometry(QtCore.QRect(0, 30, 441, 411))
        self.defauts_treeView.setObjectName("defauts_treeView")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 10, 91, 16))
        self.label.setObjectName("label")
        self.tabSecondaire.addTab(self.tab, "")
        self.tabPrincipal.addTab(self.advancedTab, "")
        self.btn_valider = QtWidgets.QPushButton(MainWindow)
        self.btn_valider.setGeometry(QtCore.QRect(370, 500, 75, 23))
        self.btn_valider.setObjectName("btn_valider")
        self.label_4 = QtWidgets.QLabel(self.descriptorsTab)
        self.label_4.setGeometry(QtCore.QRect(250, 290, 111, 16))
        self.label_4.setObjectName("label_4")
        self.expert_data_min_index = QtWidgets.QSpinBox(self.descriptorsTab)
        self.expert_data_min_index.setGeometry(QtCore.QRect(310, 310, 42, 22))
        self.expert_data_min_index.setObjectName("expert_data_min_index")
        self.expert_data_max_index = QtWidgets.QSpinBox(self.descriptorsTab)
        self.expert_data_max_index.setGeometry(QtCore.QRect(370, 310, 42, 22))
        self.expert_data_max_index.setObjectName("expert_data_max_index")
        self.label_5 = QtWidgets.QLabel(self.descriptorsTab)
        self.label_5.setGeometry(QtCore.QRect(260, 310, 47, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.descriptorsTab)
        self.label_6.setGeometry(QtCore.QRect(360, 310, 16, 21))
        self.label_6.setObjectName("label_6")
        self.retranslateUi(MainWindow)
        self.tabPrincipal.setCurrentIndex(0)
        self.tabSecondaire.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.initialise()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MLA Settings"))
        self.pb_box.setTitle(_translate("MainWindow", "Problèmes à observer"))
        self.pb_leaning_check.setText(_translate("MainWindow", "Leaning"))
        self.pb_elbow_check.setText(_translate("MainWindow", "Elbow Move"))
        self.pb_arm_check.setText(_translate("MainWindow", "Arm Alignment"))
        self.pb_javelin_check.setText(_translate("MainWindow", "Javelin"))
        self.data_box.setTitle(_translate("MainWindow", "Accès aux données"))
        self.btn_parcourir.setText(_translate("MainWindow", "Parcourir..."))
        self.msg_data_path.setText(_translate("MainWindow", "Chemin vers le dossier \"mixed\""))
        self.tabPrincipal.setTabText(self.tabPrincipal.indexOf(self.basicsTab), _translate("MainWindow", "Basique"))
        self.data_treatment_box.setTitle(_translate("MainWindow", "Traitement des données"))
        self.scale_check.setText(_translate("MainWindow", "Scale"))
        self.normalize_check.setText(_translate("MainWindow", "Normalize"))
        self.algorithms_box.setTitle(_translate("MainWindow", "Algorithmes"))
        self.comboBox.setItemText(0, _translate("MainWindow", "k-means"))
        self.comboBox.setItemText(1, _translate("MainWindow", "option 2"))
        self.comboBox.setItemText(2, _translate("MainWindow", "option 3"))
        self.comboBox.setItemText(3, _translate("MainWindow", "option 4"))
        self.label_2.setText(_translate("MainWindow", "Algorithme à utiliser :"))
        self.label_3.setText(_translate("MainWindow", "Nombre de centroïdes :"))
        self.display_box.setTitle(_translate("MainWindow", "Affichage"))
        self.display_check.setText(_translate("MainWindow", "Afficher les graphes"))
        self.tabSecondaire.setTabText(self.tabSecondaire.indexOf(self.algorithmTab), _translate("MainWindow", "Algorithmes"))
        self.data_path_label.setText(_translate("MainWindow", "Chemin :"))
        self.path_explore_button.setText(_translate("MainWindow", "Parcourir..."))
        self.load_button.setText(_translate("MainWindow", "Charger les donnees"))
        self.descriptor_label.setText(_translate("MainWindow", "Descripteur :"))
        self.add_articulation_button.setText(_translate("MainWindow", "Ajouter"))
        self.lateralite_check.setText(_translate("MainWindow", "Latéralité"))
        self.add_button.setText(_translate("MainWindow", "Ajouter"))
        self.defaut_name_label.setText(_translate("MainWindow", "Nom du défaut :"))
        self.default_tree_recap.headerItem().setText(0, _translate("MainWindow", "Descripteurs"))
        self.default_tree_recap.headerItem().setText(1, _translate("MainWindow", "Latéralité"))
        self.tabSecondaire.setTabText(self.tabSecondaire.indexOf(self.descriptorsTab), _translate("MainWindow", "Descripteurs"))
        self.label.setText(_translate("MainWindow", "Liste des défauts :"))
        self.tabSecondaire.setTabText(self.tabSecondaire.indexOf(self.tab), _translate("MainWindow", "Résumé"))
        self.tabPrincipal.setTabText(self.tabPrincipal.indexOf(self.advancedTab), _translate("MainWindow", "Avancé"))
        self.btn_valider.setText(_translate("MainWindow", "Valider"))
        self.defauts_treeView.headerItem().setText(0, _translate("MainWindow", "Défauts"))
        self.defauts_treeView.headerItem().setText(1, _translate("MainWindow", "Latéralité"))
        self.label_4.setText(_translate("MainWindow", "Données de l\'expert :"))
        self.label_5.setText(_translate("MainWindow", "De l\'index "))
        self.label_6.setText(_translate("MainWindow", "à"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
